-- 다른 세션도 동일한 시점에 TRANSACTION 을 시작!
START TRANSACTION;

-- 순자님이 커밋을 마친 상황에서 다른 세션 & 트랜잭션 상황에서 계좌를 확인!
SELECT * FROM `account`;

-- 다른 세션도 커밋을 완료 후, 계좌를 조회
COMMIT;
SELECT * FROM `account`;

-- 현재 격리 수준 확인
SELECT @@transaction_isolation;

-- 현재 세션만 변경
SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED;
SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
SET SESSION TRANSACTION ISOLATION LEVEL SERIALIZABLE;

